arb-dir: lib
template-arb-file: app_en.arb
output-localization-file: bringin_translations.dart
output-class: BringinTranslations
output-dir: lib/generated
preferred-supported-locales: ["en"]
untranslated-messages-file: untranslated_messages.txt
